name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./thesis
          root_file: main.tex
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: ./thesis/main.pdf
